### ISSUE TITLE
[leaks / 21sh / bloquant] une commande un peu longue a des risques de générer des leaks

### ISSUE THREAD

**Issue by kenjinsama** [Ninjaban/21sh#19]
La commande ci-dessous leak:
```bash
dzqdzgzhdhghzkjqgzzqgdzgjdgjgdgjgzgdjgdjgqzjdghhgdjghgdzqgjqjdgjhgdqgdjgjdgjqgjzgdjgjgjgjgdqgdgjdgqgdqgdjgdqgdjhqgjgjhdgjhgdjzjqzhdghzgdjqzgdqjdgqgdqgdhgdgdqgjdgqzdqgfjsbfgjsbnqbvjnkjsfqehjbqhgmkgjrkgmrsngjhjmrmgnkhgvdhghndbgksgnjhgfdjgrkjghskgjlhkhglkngjrlgnrbjhlkhkhkhjhjkhkhkjhjkhkjhjkhkjhkjhkjhjkhkjhjhkjhkjhkjhkjhkjhkjhkhkjhjkhjhkjhjhjkhrghrjhgjkgrhhjrrrhrhjhrhrhjdjkjkjgrjrjkrjdlrkjrjjdjrjkrjgjkjkgjkgjkrjdjgmkjgjdgjkjkdhhfesjkhfkj || test && test && test || test ; ; ; ; ; ; zqdhzhzqhzzqhkhzqjzjkkzqhzjhqzhdhqjhdqhkjhzhjfhjhkhfjhfkfehjkshgkdhgkjhfsehgksjkshghshgkhgshgkskskjghsghkegshghkjghkhgkhgshkhkghskghhgsiitubtuiuusveyrcueuseywveywvuvlevyvuwueyvlsyvuyuyvursyiwevyrwysuversiyvuebrswvrwuyysreyrwsulelyrywybusvryleyrvesuyvsyuyvribyubvuvuwyriywiueeyvusyrvuyriuyvlreuuvyurywsvbevylswylrlesbruiesyvruysyvruyryuwsyssyvruewyeueluylrywsyueurusyeyevryueuvyyyesuvrureyelrvyuysyurueuriuyyuruviryseyryrlsyrisyyeyurvuvuyeuyirqpieuivuiouuizuoreurezuiuqprepizddqiuiufeuiuiesuiefreerreuswufsueueueue,uueuefueiufeiu
```

Rapport:
dzqdzgzhdhghzkjqgzzqgdzgjdgjgdgjgzgdjgdjgqzjdghhgdjghgdzqgjqjdgjhgdqgdjgjdgjqgjzgdjgjgjgjgdqgdgjdgqgdqgdjgdqgdjhqgjgjhdgjhgdjzjqzhdghzgdjqzgdqjdgqgdqgdhgdgdqgjdgqzdqgfjsbfgjsbnqbvjnkjsfqehjbqhgmkgjrkgmrsngjhjmrmgnkhgvdhghndbgksgnjhgfdjgrkjghskgjlhkhglkngjrlgnrbjhlkhkhkhjhjkhkhkjhjkhkjhjkhkjhkjhkjhjkhkjhjhkjhkjhkjhkjhkjhkjhkhkjhjkhjhkjhjhjkhrghrjhgjkgrhhjrrrhrhjhrhrhjdjkjkjgrjrjkrjdlrkjrjjdjrjkrjgjkjkgjkgjkrjdjgmkjgjdgjkjkdhhfesjkhfkj || test && test && test || test ; ; ; ; ; ; zqdhzhzqhzzqhkhzqjzjkkzqhzjhqzhdhqjhdqhkjhzhjfhjhkhfjhfkfehjkshgkdhgkjhfsehgksjkshghshgkhgshgkskskjghsghkegshghkjghkhgkhgshkhkghskghhgsiitubtuiuusveyrcueuseywveywvuvlevyvuwueyvlsyvuyuyvursyiwevyrwysuversiyvuebrswvrwuyysreyrwsulelyrywybusvryleyrvesuyvsyuyvribyubvuvuwyriywiueeyvusyrvuyriuyvlreuuvyurywsvbevylswylrlesbruiesyvruysyvruyryuwsyssyvruewyeueluylrywsyueurusyeyevryueuvyyyesuvrureyelrvyuysyurueuriuyyuruviryseyryrlsyrisyyeyurvuvuyeuyirqpieuivuiouuizuoreurezuiuqprepizddqiuiufeuiuiesuiefreerreuswufsueueueue,uueuefueiufeiu
21sh [WARNING] : Fichier ou Executable introuvable.
21sh [ERROR]   : dzqdzgzhdhghzkjqgzzqgdzgjdgjgdgjgzgdjgdjgqzjdghhgdjghgdzqgjqjdgjhgdqgdjgjdgjqgjzgdjgjgjgjgdqgdgjdgqgdqgdjgdqgdjhqgjgjhdgjhgdjzjqzhdghzgdjqzgdqjdgqgdqgdhgdgdqgjdgqzdqgfjsbfgjsbnqbvjnkjsfqehjbqhgmkgjrkgmrsngjhjmrmgnkhgvdhghndbgksgnjhgfdjgrkjghskgjlhkhglkngjrlgnrbjhlkhkhkhjhjkhkhkjhjkhkjhjkhkjhkjhkjhjkhkjhjhkjhkjhkjhkjhkjhkjhkhkjhjkhjhkjhjhjkhrghrjhgjkgrhhjrrrhrhjhrhrhjdjkjkjgrjrjkrjdlrkjrjjdjrjkrjgjkjkgjkgjkrjdjgmkjgjdgjkjkdhhfesjkhfkj -> Commande introuvable
==15688== 
==15688== HEAP SUMMARY:
==15688==     in use at exit: 23,953 bytes in 288 blocks
==15688==   total heap usage: 5,437,361 allocs, 5,437,073 frees, 454,313,059 bytes allocated
==15688== 
==15688== 72 bytes in 19 blocks are definitely lost in loss record 39 of 69
==15688==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==15688==    by 0x40EDCC: ft_strdup (ft_strdup.c:23)
==15688==    by 0x4086C7: ft_new_node (in /home/stephane/Documents/21sh/21sh)
==15688==    by 0x4089A8: ft_init_node (in /home/stephane/Documents/21sh/21sh)
==15688==    by 0x407FAD: ft_parsing_multicmd (in /home/stephane/Documents/21sh/21sh)
==15688==    by 0x408165: ft_add_node (in /home/stephane/Documents/21sh/21sh)
==15688==    by 0x40813D: ft_add_node (in /home/stephane/Documents/21sh/21sh)
==15688==    by 0x40817E: ft_add_node (in /home/stephane/Documents/21sh/21sh)
==15688==    by 0x40813D: ft_add_node (in /home/stephane/Documents/21sh/21sh)
==15688==    by 0x40817E: ft_add_node (in /home/stephane/Documents/21sh/21sh)
==15688==    by 0x40813D: ft_add_node (in /home/stephane/Documents/21sh/21sh)
==15688==    by 0x40817E: ft_add_node (in /home/stephane/Documents/21sh/21sh)
==15688== 
==15688== 152 bytes in 19 blocks are definitely lost in loss record 48 of 69
==15688==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==15688==    by 0x40FBEA: ft_strsplit (ft_strsplit.c:89)
==15688==    by 0x408578: ft_parsecmd (in /home/stephane/Documents/21sh/21sh)
==15688==    by 0x4086CF: ft_new_node (in /home/stephane/Documents/21sh/21sh)
==15688==    by 0x4089A8: ft_init_node (in /home/stephane/Documents/21sh/21sh)
==15688==    by 0x407FAD: ft_parsing_multicmd (in /home/stephane/Documents/21sh/21sh)
==15688==    by 0x408165: ft_add_node (in /home/stephane/Documents/21sh/21sh)
==15688==    by 0x40813D: ft_add_node (in /home/stephane/Documents/21sh/21sh)
==15688==    by 0x40817E: ft_add_node (in /home/stephane/Documents/21sh/21sh)
==15688==    by 0x40813D: ft_add_node (in /home/stephane/Documents/21sh/21sh)
==15688==    by 0x40817E: ft_add_node (in /home/stephane/Documents/21sh/21sh)
==15688==    by 0x40813D: ft_add_node (in /home/stephane/Documents/21sh/21sh)
==15688== 
==15688== 154 bytes in 10 blocks are definitely lost in loss record 49 of 69
==15688==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==15688==    by 0x40F091: ft_strjoin (ft_strjoin.c:25)
==15688==    by 0x40A0A5: ft_verifpath (in /home/stephane/Documents/21sh/21sh)
==15688==    by 0x40A209: ft_getpath (in /home/stephane/Documents/21sh/21sh)
==15688==    by 0x400F70: ft_access (in /home/stephane/Documents/21sh/21sh)
==15688==    by 0x40493E: ft_exec_child (in /home/stephane/Documents/21sh/21sh)
==15688==    by 0x4045AC: ft_exec_built (in /home/stephane/Documents/21sh/21sh)
==15688==    by 0x4046E2: ft_exec_left (in /home/stephane/Documents/21sh/21sh)
==15688==    by 0x40487D: ft_exec (in /home/stephane/Documents/21sh/21sh)
==15688==    by 0x40CA00: ft_shell (in /home/stephane/Documents/21sh/21sh)
==15688==    by 0x407DFC: main (in /home/stephane/Documents/21sh/21sh)
==15688== 
==15688== 4,524 bytes in 10 blocks are definitely lost in loss record 69 of 69
==15688==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==15688==    by 0x40F091: ft_strjoin (ft_strjoin.c:25)
==15688==    by 0x400E1A: ft_trypath (in /home/stephane/Documents/21sh/21sh)
==15688==    by 0x400FC7: ft_access (in /home/stephane/Documents/21sh/21sh)
==15688==    by 0x40493E: ft_exec_child (in /home/stephane/Documents/21sh/21sh)
==15688==    by 0x4045AC: ft_exec_built (in /home/stephane/Documents/21sh/21sh)
==15688==    by 0x4046E2: ft_exec_left (in /home/stephane/Documents/21sh/21sh)
==15688==    by 0x40487D: ft_exec (in /home/stephane/Documents/21sh/21sh)
==15688==    by 0x40CA00: ft_shell (in /home/stephane/Documents/21sh/21sh)
==15688==    by 0x407DFC: main (in /home/stephane/Documents/21sh/21sh)
==15688== 
==15688== LEAK SUMMARY:
==15688==    definitely lost: 4,902 bytes in 58 blocks
==15688==    indirectly lost: 0 bytes in 0 blocks
==15688==      possibly lost: 0 bytes in 0 blocks
==15688==    still reachable: 19,051 bytes in 230 blocks
==15688==         suppressed: 0 bytes in 0 blocks
==15688== Reachable blocks (those to which a pointer was found) are not shown.
==15688== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==15688== 
==15688== For counts of detected and suppressed errors, rerun with: -v
==15688== ERROR SUMMARY: 4 errors from 4 contexts (suppressed: 0 from 0)
21sh [WARNING] : Fichier ou Executable introuvable.
21sh [ERROR]   : zqdhzhzqhzzqhkhzqjzjkkzqhzjhqzhdhqjhdqhkjhzhjfhjhkhfjhfkfehjkshgkdhgkjhfsehgksjkshghshgkhgshgkskskjghsghkegshghkjghkhgkhgshkhkghskghhgsiitubtuiuusveyrcueuseywveywvuvlevyvuwueyvlsyvuyuyvursyiwevyrwysuversiyvuebrswvrwuyysreyrwsulelyrywybusvryleyrvesuyvsyuyvribyubvuvuwyriywiueeyvusyrvuyriuyvlreuuvyurywsvbevylswylrlesbruiesyvruysyvruyryuwsyssyvruewyeueluylrywsyueurusyeyevryueuvyyyesuvrureyelrvyuysyurueuriuyyuruviryseyryrlsyrisyyeyurvuvuyeuyirqpieuivuiouuizuoreurezuiuqprepizddqiuiufeuiuiesuiefreerreuswufsueueueue,uueuefueiufeiu -> Commande introuvable
==15691== 
==15691== HEAP SUMMARY:
==15691==     in use at exit: 24,863 bytes in 288 blocks
==15691==   total heap usage: 5,437,361 allocs, 5,437,073 frees, 454,313,969 bytes allocated
==15691== 
==15691== 72 bytes in 19 blocks are definitely lost in loss record 39 of 69
==15691==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==15691==    by 0x40EDCC: ft_strdup (ft_strdup.c:23)
==15691==    by 0x4086C7: ft_new_node (in /home/stephane/Documents/21sh/21sh)
==15691==    by 0x4089A8: ft_init_node (in /home/stephane/Documents/21sh/21sh)
==15691==    by 0x407FAD: ft_parsing_multicmd (in /home/stephane/Documents/21sh/21sh)
==15691==    by 0x408165: ft_add_node (in /home/stephane/Documents/21sh/21sh)
==15691==    by 0x40813D: ft_add_node (in /home/stephane/Documents/21sh/21sh)
==15691==    by 0x40817E: ft_add_node (in /home/stephane/Documents/21sh/21sh)
==15691==    by 0x40813D: ft_add_node (in /home/stephane/Documents/21sh/21sh)
==15691==    by 0x40817E: ft_add_node (in /home/stephane/Documents/21sh/21sh)
==15691==    by 0x40813D: ft_add_node (in /home/stephane/Documents/21sh/21sh)
==15691==    by 0x40817E: ft_add_node (in /home/stephane/Documents/21sh/21sh)
==15691== 
==15691== 152 bytes in 19 blocks are definitely lost in loss record 48 of 69
==15691==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==15691==    by 0x40FBEA: ft_strsplit (ft_strsplit.c:89)
==15691==    by 0x408578: ft_parsecmd (in /home/stephane/Documents/21sh/21sh)
==15691==    by 0x4086CF: ft_new_node (in /home/stephane/Documents/21sh/21sh)
==15691==    by 0x4089A8: ft_init_node (in /home/stephane/Documents/21sh/21sh)
==15691==    by 0x407FAD: ft_parsing_multicmd (in /home/stephane/Documents/21sh/21sh)
==15691==    by 0x408165: ft_add_node (in /home/stephane/Documents/21sh/21sh)
==15691==    by 0x40813D: ft_add_node (in /home/stephane/Documents/21sh/21sh)
==15691==    by 0x40817E: ft_add_node (in /home/stephane/Documents/21sh/21sh)
==15691==    by 0x40813D: ft_add_node (in /home/stephane/Documents/21sh/21sh)
==15691==    by 0x40817E: ft_add_node (in /home/stephane/Documents/21sh/21sh)
==15691==    by 0x40813D: ft_add_node (in /home/stephane/Documents/21sh/21sh)
==15691== 
==15691== 154 bytes in 10 blocks are definitely lost in loss record 49 of 69
==15691==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==15691==    by 0x40F091: ft_strjoin (ft_strjoin.c:25)
==15691==    by 0x40A0A5: ft_verifpath (in /home/stephane/Documents/21sh/21sh)
==15691==    by 0x40A209: ft_getpath (in /home/stephane/Documents/21sh/21sh)
==15691==    by 0x400F70: ft_access (in /home/stephane/Documents/21sh/21sh)
==15691==    by 0x40493E: ft_exec_child (in /home/stephane/Documents/21sh/21sh)
==15691==    by 0x4045AC: ft_exec_built (in /home/stephane/Documents/21sh/21sh)
==15691==    by 0x4046E2: ft_exec_left (in /home/stephane/Documents/21sh/21sh)
==15691==    by 0x40487D: ft_exec (in /home/stephane/Documents/21sh/21sh)
==15691==    by 0x40CA00: ft_shell (in /home/stephane/Documents/21sh/21sh)
==15691==    by 0x407DFC: main (in /home/stephane/Documents/21sh/21sh)
==15691== 
==15691== 5,434 bytes in 10 blocks are definitely lost in loss record 69 of 69
==15691==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==15691==    by 0x40F091: ft_strjoin (ft_strjoin.c:25)
==15691==    by 0x400E1A: ft_trypath (in /home/stephane/Documents/21sh/21sh)
==15691==    by 0x400FC7: ft_access (in /home/stephane/Documents/21sh/21sh)
==15691==    by 0x40493E: ft_exec_child (in /home/stephane/Documents/21sh/21sh)
==15691==    by 0x4045AC: ft_exec_built (in /home/stephane/Documents/21sh/21sh)
==15691==    by 0x4046E2: ft_exec_left (in /home/stephane/Documents/21sh/21sh)
==15691==    by 0x40487D: ft_exec (in /home/stephane/Documents/21sh/21sh)
==15691==    by 0x40CA00: ft_shell (in /home/stephane/Documents/21sh/21sh)
==15691==    by 0x407DFC: main (in /home/stephane/Documents/21sh/21sh)
==15691== 
==15691== LEAK SUMMARY:
==15691==    definitely lost: 5,812 bytes in 58 blocks
==15691==    indirectly lost: 0 bytes in 0 blocks
==15691==      possibly lost: 0 bytes in 0 blocks
==15691==    still reachable: 19,051 bytes in 230 blocks
==15691==         suppressed: 0 bytes in 0 blocks
==15691== Reachable blocks (those to which a pointer was found) are not shown.
==15691== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==15691== 
==15691== For counts of detected and suppressed errors, rerun with: -v
==15691== ERROR SUMMARY: 4 errors from 4 contexts (suppressed: 0 from 0)
$: commande nº7 - (21sh)

**Comment by mrajaona** [comment]
Le leak vient des ; sans commandes
